<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>PingoEnemy</AssemblyName>
    <RootNamespace>PingoEnemy</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <LCGameDir Condition="'$(LCGameDir)' == ''">$(LETHAL_COMPANY_DIR)</LCGameDir>
    <LCProfileDir Condition="'$(LCProfileDir)' == ''">$(THUNDERSTORE_PROFILE_DIR)</LCProfileDir>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src\*.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(LCGameDir)' != ''">
    <Reference Include="Assembly-CSharp">
      <HintPath>$(LCGameDir)\Lethal Company_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Netcode.Runtime">
      <HintPath>$(LCGameDir)\Lethal Company_Data\Managed\Unity.Netcode.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(LCGameDir)\Lethal Company_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>$(LCGameDir)\Lethal Company_Data\Managed\UnityEngine.AIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(LCGameDir)\Lethal Company_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(LCGameDir)\Lethal Company_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(LCGameDir)\Lethal Company_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(LCGameDir)\Lethal Company_Data\Managed\Unity.InputSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>$(LCGameDir)\Lethal Company_Data\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>$(LCGameDir)\Lethal Company_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(LCGameDir)\Lethal Company_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(LCGameDir)\Lethal Company_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="'$(LCProfileDir)' != ''">
    <Reference Include="BepInEx">
      <HintPath>$(LCProfileDir)\BepInEx\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(LCProfileDir)\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="LethalLib">
      <HintPath>$(LCProfileDir)\BepInEx\plugins\Evaisa-LethalLib\LethalLib\LethalLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
